# Generated by Django 5.2.4 on 2025-09-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideimges',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
